# .github/workflows/deploy.yml

name: Deploy FastAPI App

on:
  push:
    branches:
      - main # Trigger this workflow when code is pushed to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner provided by GitHub Actions

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # Action to checkout your code from your GitHub repository
      - name: Deploy to Remote Server
        # This step uses the 'appleboy/ssh-action' to connect to your remote server
        # via SSH and execute commands to deploy your application.
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}       # Your server's IP address (from GitHub Secrets)
          username: ${{ secrets.SSH_USERNAME }} # SSH username for your server (from GitHub Secrets)
          key: ${{ secrets.SSH_PRIVATE_KEY }}   # SSH private key for authentication (from GitHub Secrets)
          port: 22                            # Standard SSH port, change if your server uses a different one
          script: |
            
            APP_DATA_DIR="/learnin-modules/docker_data_persists" 
            MAIN_GIT_REPO="/learnin-modules/jenkins-test"
            cd $MAIN_GIT_REPO
            echo "rebuilding the docker image"

            docker build -t fastapi-app:latest .

            echo "Running the new container with persistent volume..."
            
            docker run -d \
              --name fastapi-app-container \
              -p ${{ secrets.APP_PORT }}:${{ secrets.APP_PORT }} \
              -v $APP_DATA_DIR:/app/data \
              fastapi-app:latest

            echo "Deployment script finished."